spring:
  application:
    name: event-gateway

  datasource:
    url: jdbc:h2:mem:eventdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  pattern:
    console: >
      %d{yyyy-MM-dd HH:mm:ss}
      [%thread]
      %-5level
      [%X{traceId}]
      %logger
      - %msg%n

resilience4j:

  circuitbreaker:

    instances:

      accountService:

        slidingWindowSize: 5

        minimumNumberOfCalls: 3

        failureRateThreshold: 50

        waitDurationInOpenState: 30s

        permittedNumberOfCallsInHalfOpenState: 2

        automaticTransitionFromOpenToHalfOpenEnabled: true

  timelimiter:

    instances:

      accountService:

        timeoutDuration: 2s